CREATE DATABASE IF NOT EXISTS `requify_demoV0.3`;
USE `requify_demoV0.3`;

-- Desactivar llaves foráneas para evitar errores durante creación
SET FOREIGN_KEY_CHECKS = 0;

-- Borrar tablas si existen
DROP TABLE IF EXISTS RECEPCIONES_MATERIAL;
DROP TABLE IF EXISTS DETALLE_SOLICITUD;
DROP TABLE IF EXISTS HISTORIAL_ESTADOS;
DROP TABLE IF EXISTS SOLICITUDES;
DROP TABLE IF EXISTS MATERIALES;
DROP TABLE IF EXISTS TIPO_MATERIALES;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS ALUMNOS;
DROP TABLE IF EXISTS ASIGNATURAS;

-- ============================================
-- 1. TABLA: ROLES
-- ============================================
CREATE TABLE ROLES (
   ID_ROL INT NOT NULL AUTO_INCREMENT,
   NOMBRE_ROL VARCHAR(30),
   PRIMARY KEY (ID_ROL)
);

-- ============================================
-- 2. TABLA: USUARIOS
-- ============================================
CREATE TABLE USUARIOS (
   ID_USUARIO INT NOT NULL AUTO_INCREMENT,
   ID_ROL INT NOT NULL,
   USERNAME VARCHAR(50) NOT NULL UNIQUE,
   NOMBRE VARCHAR(150),
   APELLIDO VARCHAR(60),
   EMAIL VARCHAR(40),
   PASSWORD VARCHAR(255),
   ESTADO INT,
   FECHA_LOGIN DATETIME,
   FECHA_ALTA DATETIME,
   PRIMARY KEY (ID_USUARIO),
   CONSTRAINT FK_USUARIO_POSEE FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

-- ============================================
-- 3. TABLA: TIPO_MATERIALES (CATEGORÍAS)
-- ============================================
CREATE TABLE TIPO_MATERIALES (
   ID_TIPO_MATERIAL INT NOT NULL AUTO_INCREMENT,
   NOMBRE_TIPO_MATERIAL VARCHAR(30),
   CODIGO_BASE VARCHAR(10) NOT NULL,
   MAX_DIAS_PRESTAMO INT NOT NULL DEFAULT 7,
   CONSECUTIVO_ACTUAL INT NOT NULL DEFAULT 0,
   PRIMARY KEY (ID_TIPO_MATERIAL)
);

CREATE UNIQUE INDEX UK_TIPO_CODIGO_BASE ON TIPO_MATERIALES (CODIGO_BASE);
CREATE UNIQUE INDEX UK_TIPO_NOMBRE ON TIPO_MATERIALES (NOMBRE_TIPO_MATERIAL);

-- ============================================
-- 4. TABLA: MATERIALES
-- ============================================
CREATE TABLE MATERIALES (
   ID_MATERIAL INT NOT NULL AUTO_INCREMENT,
   ID_TIPO_MATERIAL INT NOT NULL,
   CODIGO VARCHAR(20) NOT NULL,
   NOMBRE VARCHAR(150),
   DESCRIPCION TEXT,
   CANTIDAD_TOTAL INT,
   CANTIDAD_DISPONIBLE INT,
   ESTADO INT,
   UBICACION VARCHAR(100),
   PRIMARY KEY (ID_MATERIAL),
   UNIQUE KEY UK_MATERIAL_CODIGO (CODIGO),
   CONSTRAINT FK_MATERIAL_TIPO FOREIGN KEY (ID_TIPO_MATERIAL) REFERENCES TIPO_MATERIALES(ID_TIPO_MATERIAL)
);

-- ============================================
-- 5. TABLA: ALUMNOS
-- ============================================
CREATE TABLE ALUMNOS (
   ID_ALUMNO INT NOT NULL AUTO_INCREMENT,
   RUT VARCHAR(12),
   NOMBRE VARCHAR(150),
   APELLIDO VARCHAR(60),
   CURSO VARCHAR(50),
   PRIMARY KEY (ID_ALUMNO)
);

-- ============================================
-- 6. TABLA: ASIGNATURAS
-- ============================================
CREATE TABLE ASIGNATURAS (
   ID_ASIGNATURA INT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR(100) NOT NULL,
   PRIMARY KEY (ID_ASIGNATURA),
   UNIQUE KEY UK_ASIGNATURA_NOMBRE (NOMBRE)
);

-- ============================================
-- 7. TABLA: SOLICITUDES (CABECERA PRÉSTAMO)
-- ============================================
CREATE TABLE SOLICITUDES (
   ID_SOLICITUD INT NOT NULL AUTO_INCREMENT,
   ID_USUARIO INT NOT NULL,
   ID_ALUMNO INT,
   ID_ASIGNATURA INT NOT NULL,
   FECHA_SOLICITUD DATETIME,
   ESTADO INT,
   FECHA_DEVOLUCION DATETIME,
   RESPONSABLE VARCHAR(100),
   OBSERVACIONES TEXT,
   PRIMARY KEY (ID_SOLICITUD),
   CONSTRAINT FK_SOL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
   CONSTRAINT FK_SOL_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO),
   CONSTRAINT FK_SOL_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURAS(ID_ASIGNATURA)
);

-- ============================================
-- 8. TABLA: DETALLE_SOLICITUD
-- ============================================
CREATE TABLE DETALLE_SOLICITUD (
   ID_DETALLE INT NOT NULL AUTO_INCREMENT,
   ID_SOLICITUD INT NOT NULL,
   ID_MATERIAL INT NOT NULL,
   CANTIDAD_SOLICITADA INT,
   CANTIDAD_ENTREGADA INT,
   ESTADO_DEVOLUCION VARCHAR(100),
   OBSERVACIONES_DEVOLUCION TEXT,
   PRIMARY KEY (ID_DETALLE),
   CONSTRAINT FK_DET_SOL FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES(ID_SOLICITUD),
   CONSTRAINT FK_DET_MAT FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIALES(ID_MATERIAL)
);

-- ============================================
-- 9. TABLA: RECEPCIONES_MATERIAL
-- ============================================
CREATE TABLE RECEPCIONES_MATERIAL (
   ID_RECEPCION INT NOT NULL AUTO_INCREMENT,
   ID_DETALLE INT NOT NULL,
   ID_USUARIO INT NOT NULL,
   CANTIDAD_RECIBIDA INT,
   ESTADO_MATERIAL VARCHAR(100),
   OBSERVACIONES TEXT,
   FECHA_RECEPCION DATETIME,
   PRIMARY KEY (ID_RECEPCION),
   CONSTRAINT FK_REC_DET FOREIGN KEY (ID_DETALLE) REFERENCES DETALLE_SOLICITUD(ID_DETALLE),
   CONSTRAINT FK_REC_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- ============================================
-- 10. TABLA: HISTORIAL_ESTADOS
-- ============================================
CREATE TABLE HISTORIAL_ESTADOS (
   ID_HISTORIAL INT NOT NULL AUTO_INCREMENT,
   ID_SOLICITUD INT NOT NULL,
   ESTADO_ANTERIOR VARCHAR(50),
   ESTADO_NUEVO VARCHAR(50),
   FECHA_CAMBIO DATETIME,
   PRIMARY KEY (ID_HISTORIAL),
   CONSTRAINT FK_HIST_SOL FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES(ID_SOLICITUD)
);

-- ============================================
-- 11. DATOS INICIALES
-- ============================================

-- Roles
INSERT INTO ROLES (NOMBRE_ROL) VALUES 
('Administrador'), 
('Encargado de Recursos');

-- Tipos de Materiales (Categorías)
INSERT INTO TIPO_MATERIALES (NOMBRE_TIPO_MATERIAL, CODIGO_BASE, MAX_DIAS_PRESTAMO, CONSECUTIVO_ACTUAL) VALUES
('Tablets', 'TAB', 7, 1),
('Notebooks', 'NBK', 10, 1),
('Libros', 'LIB', 21, 1),
('Material Deportivo', 'DEP', 5, 1);

-- Materiales
INSERT INTO MATERIALES (ID_TIPO_MATERIAL, CODIGO, NOMBRE, CANTIDAD_TOTAL, CANTIDAD_DISPONIBLE, ESTADO, UBICACION) VALUES
(1, 'TAB-001', 'Tablet Samsung Galaxy Tab A8', 20, 20, 1, 'Bodega A-1'),
(2, 'NBK-001', 'Notebook HP 14-dq2055wm', 100, 100, 1, 'Carro B-1'),
(3, 'LIB-001', 'Libro "El Quijote"', 50, 50, 1, 'Biblioteca'),
(4, 'DEP-001', 'Balón de Fútbol N°5', 30, 30, 1, 'Gimnasio');

-- Alumnos
INSERT INTO ALUMNOS (RUT, NOMBRE, APELLIDO, CURSO) VALUES
('12.345.678-9', 'Diego', 'Soto', '8° A'),
('23.456.789-0', 'María', 'Castillo', '7° B');

-- Asignaturas
INSERT INTO ASIGNATURAS (NOMBRE) VALUES
('Ciencias Naturales'),
('Educación Física'),
('Historia'),
('Inglés'),
('Lenguaje'),
('Matemáticas'),
('Tecnología');

-- Usuario Administrador
INSERT INTO USUARIOS (ID_ROL, USERNAME, NOMBRE, APELLIDO, EMAIL, PASSWORD, ESTADO, FECHA_ALTA)
VALUES (1, 'admin', 'Pedro', 'Fernández', 'admin@requify.cl', 
'pbkdf2$150000$75dceff5d82990787a9e298f0aaa5627$d18eefb092629b4281746ce2662701bc23f58e23d76dcac12390b82ec8fff576f288dcff2de19a10cd95125f99e963eae2f242b4865ac407cdef75d75f1ca6a2', 
1, NOW());

-- Reactivar llaves foráneas
SET FOREIGN_KEY_CHECKS = 1;
